"""add rassignment table

Revision ID: 82d86445123d
Revises: 187514c1b59b
Create Date: 2022-01-11 03:56:51.832446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '82d86445123d'
down_revision = '187514c1b59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rassignment',
                    sa.Column('tests_collection', sa.JSON(), nullable=True),
                    sa.Column('last_modified', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bundle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('assignment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('package_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('datasets', sa.JSON(), nullable=True),
                    sa.Column('setup_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rassignment_assignment_name'), 'rassignment', ['assignment_name'], unique=False)
    op.create_index(op.f('ix_rassignment_bundle_name'), 'rassignment', ['bundle_name'], unique=False)
    op.create_index(op.f('ix_rassignment_id'), 'rassignment', ['id'], unique=False)
    op.create_index(op.f('ix_rassignment_package_names'), 'rassignment', ['package_names'], unique=False)
    op.create_index(op.f('ix_rassignment_setup_code'), 'rassignment', ['setup_code'], unique=False)
    op.create_index(op.f('ix_rassignment_user_id'), 'rassignment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rassignment_user_id'), table_name='rassignment')
    op.drop_index(op.f('ix_rassignment_setup_code'), table_name='rassignment')
    op.drop_index(op.f('ix_rassignment_package_names'), table_name='rassignment')
    op.drop_index(op.f('ix_rassignment_id'), table_name='rassignment')
    op.drop_index(op.f('ix_rassignment_bundle_name'), table_name='rassignment')
    op.drop_index(op.f('ix_rassignment_assignment_name'), table_name='rassignment')
    op.drop_table('rassignment')
    # ### end Alembic commands ###
