"""remove comment table

Revision ID: bb73bb170130
Revises: 82d86445123d
Create Date: 2022-01-21 21:51:45.199955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bb73bb170130'
down_revision = '82d86445123d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_id', table_name='comment')
    op.drop_index('ix_comment_text', table_name='comment')
    op.drop_index('ix_comment_title', table_name='comment')
    op.drop_index('ix_comment_user_id', table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    op.create_index('ix_comment_user_id', 'comment', ['user_id'], unique=False)
    op.create_index('ix_comment_title', 'comment', ['title'], unique=False)
    op.create_index('ix_comment_text', 'comment', ['text'], unique=False)
    op.create_index('ix_comment_id', 'comment', ['id'], unique=False)
    # ### end Alembic commands ###
