"""changed foreign key constraint on RAssignment table

Revision ID: f5b08529497f
Revises: bb73bb170130
Create Date: 2022-01-27 15:39:33.729566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f5b08529497f'
down_revision = 'bb73bb170130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rassignment_user_id', table_name='rassignment')
    op.drop_constraint('rassignment_user_id_fkey', 'rassignment', type_='foreignkey')
    op.create_foreign_key(None, 'rassignment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rassignment', type_='foreignkey')
    op.create_foreign_key('rassignment_user_id_fkey', 'rassignment', 'user', ['user_id'], ['id'])
    op.create_index('ix_rassignment_user_id', 'rassignment', ['user_id'], unique=False)
    # ### end Alembic commands ###
